apiVersion: v1
kind: Pod
metadata:
  name: node-pod
spec:
  containers:
  - name: node-container
    image: node_app_roc:4.0
    env:
    - name: ENV_USERNAME
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: ENV_USERNAME
    - name: ENV_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: ENV_PASSWORD
    - name: ENV_SERVICE_URL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: ENV_SERVICE_URL