apiVersion: v1
kind: Pod
metadata:
  name: node-pod
spec:
  containers:
  - name: node-container
    image: node_app_roc:4.0
    env:
    - name: ENV_USERNAME
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: ENV_USERNAME
    - name: ENV_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: ENV_PASSWORD
    - name: ENV_SERVICE_URL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: ENV_SERVICE_URL


#apiVersion: v1
#kind: Pod
#metadata:
#  name: node-pod
#spec:
#  containers:
#  - name: node-container
#    image: node_app_roc:4.0
#    volumeMounts:
#    - name: secret-volume
#      mountPath: /etc/secret-volume
#  volumes:
#  - name: secret-volume
#    secret:
#      secretName: app-secrets